AllCops:
  Exclude:
    - vendor/**/*

Naming/MethodName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml

