AllCops:
  Include:
    - app/**/*.rb
    - spec/**/*.rb
  Exclude:
    - vendor/**/*
    - Dangerfile
  NewCops: enable

Naming/MethodName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml

