module SPACEX
  autoload :Capsules,   'spacex/capsules'
  autoload :Company,    'spacex/company'
  autoload :Cores,      'spacex/cores'
  autoload :Crew,       'spacex/crew'
  autoload :Dragons,    'spacex/dragons'
  autoload :History,    'spacex/history'
  autoload :Landpads,   'spacex/landpads'
  autoload :Launches,   'spacex/launches'
  autoload :Launchpads, 'spacex/launchpads'
  autoload :Payloads,   'spacex/payloads'
  autoload :Roadster,   'spacex/roadster'
  autoload :Rockets,    'spacex/rockets'
  autoload :Ships,      'spacex/ships'
  autoload :Starlink,   'spacex/starlink'
end
